# roles/tftp/tasks/main.yml
---

- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: tftp

- name: Configure SELinux if it is active on the system
  include_tasks: selinux.yml
  when: >
    ansible_selinux is defined
    and ansible_selinux != false
    and ansible_selinux.status == 'enabled'

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ tftp_packages }}"
  tags: tftp

- name: Ensure tftp root directory exists
  file:
    path: "{{ tftp_root_directory }}"
    state: directory
    owner: "{{ tftp_user }}"
    group: "{{ tftp_group }}"
    mode: "{{ tftp_mode }}"
    setype: "{{ tftp_setype }}"
  tags: tftp

- name: Install configuration file
  template:
    dest: "{{ tftp_config }}"
    src: systemd_tftp.service.j2
  notify:
    - restart tftp
  tags: tftp

- name: Ensure service is started
  service:
    name: "{{ tftp_service }}"
    state: started
    enabled: true
  tags: tftp

- name: Install foreman map file
  template:
    dest: "{{ tftp_foreman_map_file }}"
    src: etc_tftpd.map.j2
  notify:
    - restart tftp
  when: tftp_server_foreman_support
  tags:
    - tftp
    - foreman
